openapi: 3.0.3
info:
  title: SynthID Watermark Detection API
  version: "1.0.0"
servers:
  - url: http://localhost:8081
paths:
  /check:
    post:
      summary: Check media for SynthID watermark
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                asset:
                  type: string
                  format: binary
                mediaType:
                  type: string
                  enum: [image, video, audio]
      responses:
        '200':
          description: SynthID detection result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WatermarkResponse'
  /health:
    get:
      summary: Liveness probe
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
components:
  schemas:
    WatermarkResponse:
      type: object
      required: [present, confidence, modality, notes]
      properties:
        present:
          type: boolean
        confidence:
          type: number
          format: float
        modality:
          type: string
        notes:
          type: array
          items:
            type: string
        evidence:
          type: object
          description: Normalized evidence payload shared with orchestrator.
          additionalProperties: true
